name: projetsalon
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.3+1
  http: ^0.12.0+2
  flutter_staggered_grid_view: ^0.2.7
  splashscreen: ^1.2.0
  geolocator: ^4.0.3
  rich_alert: ^0.1.32
  font_awesome_flutter: ^8.4.0
  image_picker: ^0.5.4
  path_provider: ^0.5.0+1
  image: ^2.0.7
  flutter_responsive_screen: ^1.0.0
  sqflite: ^1.1.0
  dropdownfield: ^0.0.2
  image_ink_well: ^0.1.0
  charts_flutter: ^0.6.0
  flutter_section_table_view: ^1.0.5
  async: ^2.2.0
  cached_network_image: ^0.8.0
  device_calendar: ^0.0.2
  datetime_picker_formfield: ^0.1.8
  intl: ^0.15.8
  flutter_advanced_networkimage: ^0.4.15
  flutter_html: ^0.9.9
  bezier_chart:
  reorderables: ^0.2.12

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/appbar.png
    - assets/launch.png
    - assets/catalog.png
    - assets/appbar.svg
    - assets/téléchargement.png
    - assets/image.png
  # To add assets to your application, add an assets section, like this:

  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Vonique 64
      fonts:
        - asset: assets/Vonique 64.ttf
        - asset: assets/Vonique 64 Italic.ttf
        - asset: assets/Vonique 64 Bold Italic.ttf
        - asset: assets/Vonique 64 Bold.ttf

    - family: AlexandriaFLF
      fonts:
        - asset: assets/AlexandriaFLF.ttf
        - asset: assets/AlexandriaFLF-BoldItalic.ttf
        - asset: assets/AlexandriaFLF-Bold.ttf
        - asset: assets/Vonique 64 Italic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
